services:
  bot:
    build: .
    env_file: 
      - .env       # Load environment variables from .env file
    restart: always
    depends_on: 
      - redis
    ports: 
      - "8000:8000"
  redis:
    image: redis:7-alpine
    restart: always